### PR TITLE
Fixing a few typos. No functional changes.

### PR DESCRIPTION
**Pull request by seanhussey**

### CODE REVIEW

**Comment by seanhussey** [comment]
I also found inconsistency in how "thenable" was spelled. In some areas it's with one n. Other areas it has 2. I don't know what the correct spelling should be. If you do, let me know and I'd be happy to add those changes to this PR.

**Comment by isiahmeadows** [comment]
@seanhussey It should only have one "n". Everything else LGTM.

**Comment by seanhussey** [comment]
Ok, I've made those changes as well.

**Comment by isiahmeadows** [comment]
I think it's ready now.

**Pull request merged**
