### PR TITLE
[rewrite] router cleanup

### PR DESCRIPTION
**Pull request by pygy**
A few tweaks. 

The first patch adds three bytes mingzipped, but avoids mutating user-provided objects.

The second one shaves about 30.

### CODE REVIEW

**Comment by lhorie** [comment]
@pygy rocks the world again

**Comment by pygy** [comment]
Aaargh, I think this introduced a new race condition...

- `route.set('/delayedResolution')` where `onmatch` returns a pending promise.
- before that route resolves, call `route.set('/anotherRoute')` which resolves promptly.
- when the first route resolve, its `update` will stomp on `/anotherRoute`. :-/

I can't test it now, though I must get up early tomorrow morning and it's getting late.

**Comment by tivac** [comment]
What would be the expected result for that sequence?

I don't think preventing `m.route.set` while an `onmatch` is waiting to resolve is a good experience. Throwing away pending `onmatch` resolutions if a `m.route.set` call comes through doesn't seem great either.

**Comment by barneycarroll** [comment]
Any given set request should always be given priority and cancel all pending sets.

**Comment by tivac** [comment]
Then Promises seem problematic given their inability to be cancelled.

**Comment by tivac** [comment]
Oh, I should've looked. There's already a test for that behavior.

https://github.com/lhorie/mithril.js/blob/rewrite/api/tests/test-router.js#L642-L670

**Comment by lhorie** [comment]
yeah I noticed that just a while ago, I'm working on a fix

**Pull request merged**
