### PR TITLE
[rewrite] handle fragmented attrs and children

### PR DESCRIPTION
**Pull request by SamuelTilly**
Handle fragmented attributes so that there is no need for end-users to depend on merging libraries or polyfills.

### CODE REVIEW

**Comment by darsain** [comment]
This is redundant. You don't need libraries, just JS:

```js
m("div", {...a, ...b, c: 'd'});
```

Which effectively does:

```js
m("div", Object.assign({}, a, b, {c: 'd'}));
```

This PR would extend the API surface area to provide features that are (or *will* be if you are a no-babel using caveman 😄) build into the language itself.

**Comment by SamuelTilly** [comment]
I'm a no-babel using caveman :wave:

**Comment by CYBAI** [comment]
Will it be better to use polyfill of `isArray` as same as MDN?

Ref: [Array.isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)

**Comment by isiahmeadows** [comment]
The polyfill isn't necessary: IE 9, the new baseline, already supports it
natively by default.

**Comment by lhorie** [comment]
I think this is unnecessary, given there's already a plethora of alternatives that do the same thing (`Object.assign`, `_.assign`, `$.extend`, `R.merge`, object spread operator proposal in stage 3, etc...)

Another problem I spotted is that the refactoring introduced in this PR makes `m()` almost twice as slow as it is now

**Comment by SamuelTilly** [comment]
@lhorie how are you running benchmarks on the code? from just running the test i didn't see any difference in performance, sometimes even executed faster then previously.

**Comment by lhorie** [comment]
You can see the difference by doing something like this:

```javascript
console.time()
for (var i = 0; i < 10000; i++) {
  m("div", {class: "a"}, "b") // you can try with different variations
}
console.timeEnd()
```

Were you running the entire test suite via `npm test`? It does a lot of async things (and that's why it takes a few seconds). Those other tests dwarf the hyperscript test times by a few orders of magnitude.

**Pull request closed without merging**
