### PR TITLE
prepublish task for npm

### PR DESCRIPTION
**Pull request by ludbek**

### CODE REVIEW

**Comment by ludbek** [comment]
It seems lint is failing. Is it deliberately left for final clean up?

**Comment by tivac** [comment]
Now that travis auto-commits the bundled files after successful builds is this necessary? I have concerns, mostly around how [`prepublish` is not usually what people expect it to be.](https://github.com/npm/npm/issues/10074)

**Comment by pygy** [comment]
There's actually a ["in-publish" NPM pacakge](https://www.npmjs.com/package/in-publish) just for that:

```JSON
{
  "scripts": {
    "prepublish": "in-publish && thing-I-dont-want-on-dev-install || not-in-publish"
  }
}
```

**Comment by tivac** [comment]
@pygy Yes, but using [`preversion`](https://github.com/npm/npm/issues/8402#issuecomment-119059597) is IMO more correct if we want to have automated checks.

It's an academic point though, @lhorie's the only one w/ NPM publish rights and I'm not sure what his process is. In my ideal world we would publish via travis by pushing a tag so that there's zero dependencies on specific computers/processes and it's as automated as possible.

**Comment by tivac** [comment]
Pinging @lhorie one last time to see if this sort of build automation if something he wants.

**Comment by tivac** [comment]
Closing for now due to a lack of interest from the sole npm publisher.

**Pull request closed without merging**
