### PR TITLE
[next] Unmount cleanup  (#727 regression)

### PR DESCRIPTION
**Pull request by pygy**
Since `roots` and friends are private, I don't think it's possible to write tests to prevent future regressions...

### CODE REVIEW

**Comment by ketan** [comment]
> Since roots and friends are private, I don't think it's possible to write tests to prevent future regressions...

Is there any interest in implementing an `m.reset` that could be used inside tests to help clean up this internal state, among any other state? It's only in tests that we're really having to unmount and the tests get progressively slower because of all sorts of leaks.

For e.g. one problem we see is how to cleanly unmount routes. We're having to resort to really ugly hacks, to undo the effect of [this code](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1630-L1634), by setting `window. onhashchange` to `null` before and after each test.

**Comment by barneycarroll** [comment]
@ketan could you elaborate on the problem?

I'm suffering problems in writing tests for a routing plugin on top of the bundled Mithril v1 and start to see weird behaviour after several route mounts… https://github.com/barneycarroll/mithril-route-components/blob/master/tests/index.js

**Comment by pygy** [comment]
@barneycarroll did you try #1290?

**Comment by barneycarroll** [comment]
@pygy I'll try it, thanks. So much going on in routing!

**Comment by pygy** [comment]
Note that CI failed due to a botched NPM install, the tests pass locally...

**Comment by pygy** [comment]
Travis appears to be picky regarding proper variable naming.

I replaced `dummy` with `dummyComponent` and rebased on top of the git HEAD.

CI now passes ¯\\\_(ツ)_/¯

**Comment by pygy** [comment]
Closing for now, as I'm about to revamp `mount` in a slightly more invasive way.

The regression stems from [this "linting" commit](https://github.com/lhorie/mithril.js/commit/0766d93bacac454be74ffdc815c099d898abe478) that also caused one half of the #348 regression. That commit is all but impossible to review, I wonder what else is hiding in there.

**Comment by tivac** [comment]
there be dragons

**Pull request closed without merging**
