### PR TITLE
Remove typescript definitions

### PR DESCRIPTION
**Pull request by spacejack**
This is a pull request following up on: https://github.com/lhorie/mithril.js/pull/1688#issuecomment-285235535

### CODE REVIEW

**Comment by bduisenov** [comment]
Hi @spacejack, where you want to move types to?

**Comment by spacejack** [comment]
They would be added to the DefinitelyTyped repo, which means you'd install them like:

    npm install @types/mithril

**Comment by andraaspar** [comment]
@spacejack Would you like to continue developing the improved definitions in [your repo](https://github.com/spacejack/mithril.d.ts/tree/improved)?

**Comment by spacejack** [comment]
@andraaspar Sure that would be great. I'll add you as a maintainer there.

**Pull request merged**
