### PR TITLE
Update link pointing to how to use the optional Streams module

### PR DESCRIPTION
**Pull request by iamsumanth**

### CODE REVIEW

**Comment by tivac** [comment]
This fix already landed on `next` but since folks are apparently still looking at `rewrite` it doesn't hurt to fix it there too. Thanks!

**Comment by iamsumanth** [comment]
I think direction to ```rewrite``` comes from https://www.npmjs.com/package/mithril-codemods at least in my case.

**Comment by isiahmeadows** [comment]
@tivac tivac/mithril-codemods#27 (Welcome.)

**Comment by isiahmeadows** [comment]
There's likely others to update, too.

**Pull request merged**
