### PR TITLE
More performance improvements + etc. [WIP]

### PR DESCRIPTION
**Pull request by isiahmeadows**
Continuation of #887. It was merged prematurely.

**Note: this is still a work in progress.**

### CODE REVIEW

**Comment by StephanHoyer** [comment]
give a `[WIP]` prefix to the PR to avoid merge

**Comment by isiahmeadows** [comment]
Note that this is fixing problems with #887.

**Comment by lhorie** [comment]
What are the problems? @isiahmeadows

**Comment by isiahmeadows** [comment]
The build was breaking.

**Comment by isiahmeadows** [comment]
And tests failing locally.

**Comment by lhorie** [comment]
Ok, so is this PR ready to merge?

**Comment by isiahmeadows** [comment]
@lhorie If these tests pass, then yes, it's finally ready. :frowning: :hand:

**Comment by isiahmeadows** [comment]
Merging the fix now.

**Comment by lhorie** [comment]
awesome, thanks

**Comment by isiahmeadows** [comment]
Welcome. Sometimes, I feel like a dumbass, and this is one of them. :frowning: The bug was actually in m.request, where I misread a condition as its negation (or `!a && !b` is equivalent to `!(a || b)`, not `a || b`), and erroneously tried to optimize that out by sticking in a default.

**Comment by lhorie** [comment]
Meh, everyone makes mistakes. Don't worry about it. You've been doing a great job :)

**Comment by isiahmeadows** [comment]
@lhorie Thanks

**Pull request merged**
