### PR TITLE
Overwrite an element's style using cssText (with tests fixed).

### PR DESCRIPTION
**Pull request by pygy**
Builds on #1219, fix the mocks.

### CODE REVIEW

**Comment by pygy** [comment]
For some reason, once again, I can't send a PR to @mindeavor directly.

**Comment by isiahmeadows** [comment]
@pygy Is it that you aren't forking from [mindeavor's fork](https://github.com/mindeavor/mithril.js) and following up with a PR there?

**Comment by pygy** [comment]
Indeed, I've forked the main repo.

What's strange is that there's a arge list of "base fork" options, but the one I'm looking for is never there.

**Comment by isiahmeadows** [comment]
I usually just make a full fresh clone to wherever (you can clone to custom directories pretty easily in Git), and have everything automagically set to what I need there. The directory might not be the main repo's name, but it works.

**Comment by pygy** [comment]
So I could clone the PR repo, add my fork of Leo's repo (`pygy/mithril.js`) as a remote to the PR local clone, and push the changes to `pygy/mithril.js`? Then I could open a PR on the PR?

The only time I successfully sent a PR on a PR it was to you, but I had forked your repo on GH to `j2c/mithril.js`... If I understand you correctly, that step is not needed. Is that right?

**Comment by isiahmeadows** [comment]
@pygy Try this:

```sh
cd /your/mithril.js/directory

# Add his repo and fetch. The `-f` makes this also fetch the data, and the `-t` is
# so you're only tracking that particular branch, not *all* his development work.
git remote add -f mindeavor -t mindeavor/some-patch https://github.com/mindeavor/mithril.js.git

# Checkout his branch and create a local branch out of it.
git checkout -b mindeavor/some-patch mindeavor-patch

# Make your suggested changes
npm install
# hack, hack, hack
npm test

# Push to your own repo
git push -u origin mindeavor-patch

# Send him a pull request from that branch

# Once you're done with that branch locally, you can delete it and the remote
# reference to his repo:
git branch -d mindeavor-patch
git remote remove mindeavor
```

**Comment by isiahmeadows** [comment]
Git optimizes for the common case, so it's easy to send simple PRs directly, but it's still possible to keep branches in sync with other remotes.

**Comment by pygy** [comment]
That's mostly what I do currently (I didn't know about `-t` I was pulling single branches manually). The trouble is that when I push to `pygy` (`origin` is `lhorie`) I can't set the "base fork" option to `mindeavour` in the GitHub interface. There are dozens of forks available, but neither are yours nor Gilbert's or e.g. Pat's.

**Comment by isiahmeadows** [comment]
@pygy Yeah...that's an issue with GitHub itself. It's already an annoyance to file any PR against the `rewrite` branch, simply because I have to wait for the large diff computation to give up after freezing my computer before I can change branches, so I can see how that would be a pain. :frowning:

**Comment by barneycarroll** [comment]
@isiahmeadows use a bookmark, and switch your branch name as necessary: https://github.com/lhorie/mithril.js/compare/rewrite...isiahmeadows:rewrite

**Pull request merged**
