### PR TITLE
Fix an `m.withAttr` test to check the correct `this`

### PR DESCRIPTION
**Pull request by impinball**

### CODE REVIEW

**Comment by impinball** [comment]
@lhorie I'm surprised these tests even passed.

**Comment by pelonpelon** [comment]
@impinball - That's my fault. I did a cut-and-paste from another test in the file. Irresponsible, I know. I look forward to using an established test suite. Thanks for catching my FU.

**Comment by impinball** [comment]
@pelonpelon You're good! :wink:

**Comment by impinball** [comment]
@lhorie Ping

**Comment by impinball** [comment]
@lhorie Ping

**Comment by impinball** [comment]
Closing since the changes are also incorporated into my big test-rewriting PR in #822.

**Pull request closed without merging**
