### PR TITLE
Convert tests to Mocha/Chai/Sinon and lint them.

### PR DESCRIPTION
**Pull request by impinball**
@lhorie PTAL. You'll like this.

Fixes: #801, most of #706 

### Details:

1. All tests now live in `test`. All test dependencies that aren't from npm live in `test-deps`.

2. The QUnit tests are gone, as well as their dependencies. Half of them duplicated existing tests, and some of them depended on the real DOM to properly test.

3. All tests are now using Mocha to run the tests, Chai for assertions, and Sinon and Sinon Chai for testing some callbacks.

4. Tests are run through mocha-phantomjs. If you want to run just the tests, run `grunt mocha_phantomjs` or fire up a server in the root and open `http://localhost:<port>/test/index.html`, e.g. `python3 -m http.server`.

5. The linter I chose is ESLint. It is relatively easy to configure, but with a lot of flexibility. The rules I chose mostly were in tune to the style the project was already using. I'm not including a style guide in this commit, but one will likely come. You can check out the `.eslintrc` in the root and in `test/` for the two configs. The `.eslintignore` includes a TODO for `mithril.js` itself targeted at me, in the root.

Other info:

- As a drive-by fix, I fixed line endings on a few of the files.

- I also took care of a few other files and linted them as I went:

  - `Gruntfile.js`
  - `test/input-cursor.html` (was in `tests/`)
  - `test/svg.html` (was in `tests/`)
  - `docs/layout/tools/template-converter.html`
  - `docs/layout/tools/template-converter.js`

  I didn't test the template converter after linting it, because it needs further scrutiny to ensure it works with the latest version of Mithril. I know the API has changed a little, which is why I want to be sure.

- I simplified the `.travis.yml` file because none of the tests are run directly through Node anymore. They are always run in a browser of some kind.

- I fixed a lot of the Saucelabs code to reflect on the new state.

Hopefully, this turned out all right...

*(Note that for now, there are a couple TODO/FIXME/etc. related warnings. I can remove that if you would prefer, since they're only there to nag at fixing them.)*

### CODE REVIEW

**Comment by barneycarroll** [comment]
Amazing! Full merge ahead!

**Comment by tinchoz49** [comment]
eslint rocks! good job @impinball !

**Comment by impinball** [comment]
I also have a few follow-up bugs to file.

**Comment by lhorie** [comment]
wow, this is huge. Thanks @impinball

**Comment by impinball** [comment]
Welcome!

**Comment by impinball** [comment]
Here's my follow-ups: #824, #825, and #826.

Each of the tests are either commented out or disabled at the moment. I'll re-enable them real quick.

**Comment by veggiemonk** [comment]
@impinball Great work on those automated tests!!
If you don't mind my asking how much time did you spent on it ? I am really curious about it because often the main concerns when writing tests for a new app ( or your old ones ) is "it is going to take too much time", right?

I know I might sound like an interviewer after a game but: what was the hardest part (challenges) ?

On the more technical/practical side, how do you go about testing mithril component ? I put this question as a side note because I don't know if anything different is required. I see in the test you created your own `window` object. Attached to it, was `window.mock` object. Is it special to mithril?

Thanks in advance,

Again, great work.

**Comment by impinball** [comment]
To convert it all, it took about 3 1/2 days, 12 or so hours each day,
without working on anything else. I did this from home, in a stretch I had
little else to do. It wasn't at all trivial.

And as for testing components and mock objects for that, that's too high
level for testing Mithril itself. I don't know of anything specific right
off, but I could look up ways pretty quick later. The window.mock object is
specific to Mithril, for better control over requestAnimationFrame timing.
It's used for testing Mithril internally, but isn't likely helpful for
application testing, unless you're building your own testing framework. The
only change I made beyond style and an added TODO was correctly implement
requestAnimationFrame. The old implementation was brittle, but the spec is
simple.

As for difficulties, it was mostly in inferring names from tests without
them. The majority of them weren't named. I also simplified the test cases
themselves through abstracting common idioms, but I did that to also help
with coming up with names.

The other issue I had was figuring out how to simulate key presses, for two
input related tests for m.mount.

And thank you/you're welcome.

**Comment by veggiemonk** [comment]
Thanks for the feedback. Appreciated it.

**Pull request merged**
