### PR TITLE
Allow m.route links to be opened in a new window using the shift key

### PR DESCRIPTION
**Pull request by tobscure**

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Could you fix the merge conflicts? I'd be happy to merge it then!

**Comment by lhorie** [comment]
Merged. Thanks!

**Comment by lhorie** [comment]
btw, this is not a breaking change, not sure why that label was added

**Comment by isiahmeadows** [comment]
@lhorie It is slightly, if users were listening for key presses, but I see
what you mean.

**Comment by lhorie** [comment]
A breaking change usually means an API change where something gets deprecated in favor of a new alternative, or a change in semantics that requires migration steps in app space. I'd say this is more of a bug fix, since the purpose of this code is to allow m.routed links to emulate modified click behavior of regular links and the 2 other cases were already being handled.

**Comment by isiahmeadows** [comment]
Okay. I see now. Thanks.

**Pull request merged**
