### PR TITLE
Use HTML / JSX as appropriate instead of 'markup'

### PR DESCRIPTION
**Pull request by barneycarroll**

### CODE REVIEW

**Comment by lhorie** [comment]
"markup" is what Prism.js uses to syntax-highlight html

**Comment by isiahmeadows** [comment]
@lhorie But it isn't correct for JSX, because that has its own grammar independent of HTML (you still have to highlight if-else statements, for example).

**Comment by lhorie** [comment]
@isiahmeadows yeah I'm fine w/ `s/markup/jsx` for that block. I'm just saying the rest won't get highlighted if they are `html` instead of `markup`

**Comment by lhorie** [comment]
Just gonna go ahead and merge, and fix on my end

**Pull request merged**
