### PR TITLE
Forgot to assign the default argument

### LINKED ISSUE #718: Dead code
@impinball, I didn't get a chance to look at all the changes you made in #713, but I did notice that the argument naming produced a line that was just `arg1 || {}` with no assignment: [see here](https://github.com/impinball/mithril.js/commit/b28045aa60f3a0aa8d253b7713bb11e4dbf03fe9#diff-0bf87cbdb33b829b275ac7973ba7bc1bR745).

It looks like the original assignment, before #713, wasn't actually necessary.  It's being removed in uglify anyways.

### PR DESCRIPTION
**Pull request by impinball**
Fixes #718. Prefer this to #719, as it repairs the lost semantics that were there before.

### CODE REVIEW

**Comment by venning** [comment]
I believe that actually breaks the original semantics...

**Comment by impinball** [comment]
Compare to [the old revision](https://github.com/lhorie/mithril.js/blob/919f443099c72604a8c76a2ac5641f72b7ff6755/mithril.js#L729).

**Comment by impinball** [comment]
@venning Check the latest push...That was what I referenced. (Sent the message before GitHub updated itself.)

**Comment by impinball** [comment]
It should be fixed now.

**Comment by venning** [comment]
Okay, so I see that change, but I think you mean `for (var i in args) params[i] = args[i];` not `for (var i in arg1) params[i] = args[i];`, right?

But more to the point, I believe that the creation of `args` (in your most recent PR) produces no side effects.  If `arg1` is truthy then the `for...in` is still running through `arg1`, if `arg1` is falsy, then the `for...in` is running through `{}` which causes zero iterations, the same as if you had left `arg1` alone and not re-assigned it to `{}`, right?  To be clear, I'm arguing that the original semantics actually contained unnecessary code which we can safely remove.  Please correct me if my JS-fu is weak here.

**Comment by impinball** [comment]
@venning 

> Okay, so I see that change, but I think you mean for (var i in args) params[i] = args[i]; not for (var i in arg1) params[i] = args[i];, right?

Oops...should be fixed now.

> But more to the point, I believe that the creation of args (in your most recent PR) produces no side effects. If arg1 is truthy then the for...in is still running through arg1, if arg1 is falsy, then the for...in is running through {} which causes zero iterations, the same as if you had left arg1 alone and not re-assigned it to {}, right? To be clear, I'm arguing that the original semantics actually contained unnecessary code which we can safely remove. Please correct me if my JS-fu is weak here.

That is correct, but I don't think the loss of clarity is worth the ~5 compressed (or ~15 minified) bytes saved.

```js
for (var i in arg1 || {}) params[i] = arg1[i];
```

**Comment by venning** [comment]
That's not exactly what I'm saying.  I believe that 
```javascript
for (var i in arg1 || {}) params[i] = arg1[i];
```
is functionally equivalent to
```javascript
for (var i in arg1) params[i] = arg1[i];
```
or am I missing something?  What values could `arg1` have that would produce a different result between those lines?

My original PR (#719) intentionally eliminated a line.

**Comment by venning** [comment]
(Whoops, commented too early.)

I agree with you, loss of clarity isn't worth it here.  I'm just saying that we have a default assignment that isn't necessary.  Eliminating the line *should* add clarity.

**Comment by impinball** [comment]
@venning They are not. What if `root` is a string, and `arg1` is `null`?

**Comment by impinball** [comment]
And as for clarity, I'm going to let @lhorie weigh on that.

**Comment by venning** [comment]
Umm, I believe that `for (var i in null)` is the same as `for (var i in {})`.  Zero iterations, zero evaluations, zero throws, zero side effects.  Therefore `for (var i in null || {})` should be an unnecessary defaulting.

Is there a browser for which a `for...in` loop behaves differently?

I'm not trying to be obsinate, but if I fundamentally misunderstand a Javascript feature (very possible), then I'd like to correct my understanding.

**Comment by impinball** [comment]
`for (var i in null) {}` should throw a TypeError according to ES3, which old IE implements (sometimes incorrectly). That behavior changed in ES5 for `null` and `undefined` to return early with 0 iterations, but Mithril is written to be mostly IE-proof.

**Comment by impinball** [comment]
See section "12.6.4 The for-in Statement" in [the ES3 spec](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf). @lhorie's rewrite will, by the sounds of it, drop legacy support, but the current one does, IIRC.

**Comment by venning** [comment]
Ahhh.  Thank you.  That's very helpful.  Thanks for bearing with me, @impinball.

:+1:

**Pull request merged**
