### PR TITLE
Can anyone remove this?

### PR DESCRIPTION
**Pull request by hugufc**

### CODE REVIEW

**Comment by pygy** [comment]
Wow, you just broke Github, now it's rambling incoherently...

**Comment by hugufc** [comment]
I just try to change docs... lol

**Comment by hugufc** [comment]
#1341 is the correct pull request.. Please disregard this..

**Comment by pygy** [comment]
From the branch name, I suppose you made the edit through the Web interface... that's weird.

**Comment by hugufc** [comment]
Yeah.. badge of shame for me... lol

**Comment by pygy** [comment]
Not really, it happens to me periodically when I rebase local branches to clean up history, but ususally `git rebase rewrite` solves it. What's weird is that it was triggered through the Web interface...

**Pull request closed without merging**
