### PR TITLE
Re-enable the test suite

### PR DESCRIPTION
**Pull request by pygy**
Edit: I'll put the potentially contentious parts in another PR.

### CODE REVIEW

**Comment by tivac** [comment]
Good catch! We should probably investigate something like [`danger`](https://github.com/danger/danger-js/) to warn about these sorts of issues.

**Comment by pygy** [comment]
I noticed it because I had tests that I expected to fail but no errors...

Is is possible to set up danger as a commit/push hook as well?

**Comment by tivac** [comment]
Not sure, afaik it's mostly intended for keeping PRs sane. IMO no one should be checking anything but documentation directly into `next` anyways.

**Comment by isiahmeadows** [comment]
@pygy I'm going to presume #1617 is related, am I correct in this?

**Comment by pygy** [comment]
@isiahmeadows indeed, it was originally part of this PR, but while what remains here was uncontroversial and could be merged by anyone, #1617 was material for Leo, hence the split.

**Pull request merged**
