### PR TITLE
Fix state initialization

### LINKED ISSUE #1638: For components, vnode.attrs.oninit and vnode.attrs.oncreate don't recieve the proper context/vnode.state
These methods are [called / scheduled](https://github.com/lhorie/mithril.js/blob/3f3af74dde47a2c538944ac6b8c29a4056967a3c/render/render.js#L23) with `vnode.state` bound as `this` before the correct `vnode.state` is initialized in `createComponent`.

The fix isn't hard (the `initLifecycle()` call must duplicated, placed once one line below its current place and once in `createComponent`), but the tests need more work.

There was a reason for the shallow copy business, after all...

### PR DESCRIPTION
**Pull request by pygy**
This builds on top of #1643 and fixes #1638 and #1641 

The tests for #1641 are fairly minimal... I may add a `test-recycling.js` file at some point (to get a better hang of how it works and systematically centralize knowledge about how the recycling pool works).

Edit: Over #1643:
- [this reworks the tests a bit more substantially](https://github.com/lhorie/mithril.js/pull/1652/commits/1dd5fe310127557ad19c679f9115a05981e0518e) and 
- [these are the #1638 and #1641 -related changes](https://github.com/lhorie/mithril.js/pull/1652/files/1dd5fe310127557ad19c679f9115a05981e0518e..ca5c68ae8a109306bc6511b52b4af8d129255e9f)

Edit2: I refactored the final commit to save a few bytes and branches.

### CODE REVIEW

**Comment by isiahmeadows** [comment]
That's a large patch...but from my initial impression, LGTM. I didn't do a proper review of it, though.

**Comment by pygy** [comment]
I'm sorry for the extra workload, but I couldn't have divided it in independent patches, they build upon one another.

The commits in #1643 (up to 2196f5c)should IMO be reviewed piecewise with `?w=1`, the changes become homogenous and easier to review... That's why I didn't rebase them before submitting the PR.

Likewise for the changes from this PR... The largest diff is 1dd5fe3. 

After that, the tests and fixes for #1638 and #1641 are actually smaller than I would have expected.

I've made minor edits to the last commit and rebased, but I won't do it anymore starting from now.

**Comment by barneycarroll** [comment]
This looks great to me – very nice work @pygy. [test-utils/components](https://github.com/pygy/mithril.js/blob/ca5c68ae8a109306bc6511b52b4af8d129255e9f/test-utils/components.js) is a robust and elegant way of formalising the tests, but it's also convoluted and doesn't resemble user-land code – it's effectively mocking invocation scenarios.

What about chucking in a simple manual view definition & mount for each to add a bit of smoke-testing for usable scenarios?

**Comment by pygy** [comment]
It automates what I would do by hand to create each kind of component with the given methods...

I could actually get rid of the default `view` and return the passed `methods` for the POJO case... would that make you feel better?

**Comment by barneycarroll** [comment]
Can't wait for the support requests we'll get when the masses lay their hands on the holy grail of Class components ;P

```javascript
// POJO
var Component = {
  data: 'Initial content',
  view: function(vnode) {
    return m('div', vnode.state.data)
  }
}

// Prototype
var Component = Object.create({
  data: 'Initial content',
  view: function(vnode) {
    return m('div', vnode.state.data)
  }
})

// Class
const data = 'Initial content'

class Component {
  get data(){
    return this.data || data
  }

  set data(value){
    this.data = value
  }

  view(vnode) {
    return m('div', vnode.state.data)
  }
}

// Factory
function Component(){
  let data = 'Initial content'

  return {
    view: function() {
      return m('div', data)
    }
  }
}
```

**Comment by isiahmeadows** [comment]
@barneycarroll 

> Can't wait for the support requests we'll get when the masses lay their hands on the holy grail of Class components ;P

Classical inheritance is powerful, you know. It's powerful enough to drastically reduce needed code in several cases, but also powerful enough to blow your entire leg off. Problem is, it's heavy enough to require quite a bit of discipline and willpower to actually hit your target, not your foot. Kind of like C++ templates and Lisp macros.

**Comment by isiahmeadows** [comment]
@barneycarroll 

> Can't wait for the support requests we'll get when the masses lay their hands on the holy grail of Class components ;P

Classical inheritance is powerful, you know. It's powerful enough to drastically reduce needed code in several cases, but also powerful enough to blow your entire leg off. Problem is, it's heavy enough to require quite a bit of discipline and willpower to actually hit your target, not your foot. Kind of like C++ templates and Lisp macros.

But let's not degrade those who don't fully know this. Best to let people learn instead of trying to shield them from their mistakes.

**Comment by lhorie** [comment]
@pygy Do you still have anything to do here or is this mergeable? I'm seeing a silly conflict, but if it's ready, I can go ahead and resolve on my end

**Comment by pygy** [comment]
@lhorie this is ready, and I've removed the built files that had slipped in the last commit

**Comment by pygy** [comment]
@barneycarroll The tests are supposed to run in ES5 environments (IE), so the `class` test requires `eval` and support guards.

The factory test would only ever break (vs `test-utils/components`) if a JS implementation had broken closures, but then it wouldn't be a JS implementation proper.

I have a few other component tests to add (for a future PR), I'll add a guarded `class` test.

**Comment by pygy** [comment]
@isiahmeadows I'm happy you merged this, but a bit surprised that you rebased everything... We end up with a large diff that mixes code changes and cleanups/refactorings, that's IMO not ideal.

**Comment by isiahmeadows** [comment]
@pygy I rebased it fairly blindly, only really seeing the 15 seemingly related commits. Sorry about that.

**Comment by pygy** [comment]
@isiahmeadows you're forgiven :-) (I see you've opened a branch to revert the merge, that's great)

For smaller, self-contained PRs, I usually only submit two or three commits (tests, code, docs?), and squashing them together doesn't hurt, but here the full history was kept on purpose, both for review and future bisecting if it introduced bugs...

**Comment by isiahmeadows** [comment]
@pygy Fixed with a little bit of git CLI wizardry.

**Comment by isiahmeadows** [comment]
I just rewrote the immediate history to use the merged output instead.

**Comment by pygy** [comment]
@isiahmeadows The changes after 2196f5c have not been merged. It looks like you only merged #1643

**Comment by isiahmeadows** [comment]
@pygy Could you file a new PR for that? I'll merge it ASAP.

**Pull request merged**
