### PR TITLE
implove for loop performance

### PR DESCRIPTION
**Pull request by bokuweb**
cache array.length property to speed up for loop.

- before
``` javascript
for (var i = 0; i < list.length; i++) {
   /* */
}
```

- after
``` javascript
for (var i = 0, len = list.length; i < len; i++) {
   /* */
}
```

### CODE REVIEW

**Comment by pygy** [comment]
This may speed up IE8 (not even sure), but that's about it. Modern JS
engines hoist the length automatically at JIT time if they determine that
the array size doesn't change during the loop.

—Pierre-Yves

**Comment by bokuweb** [comment]
I see. In considering the readability, what of such should avoid such a change?

**Comment by impinball** [comment]
That speeds up IE8/9/10 and very old Chrome/FF versions. Every other engine is smart enough to spot the loop invariant here, so it doesn't really matter. Could you show with benchmarks that this actually makes a difference in the code? I'm looking for more than microbenchmarks between the two loop forms, which I understand to be identical at even that level.

**Comment by bokuweb** [comment]
It was confirmed that there is no difference in speed with the latest version chrome.In consideration of readability and if so, it is considered that there is better not to change.I close this PR.I'm sorry.

**Comment by impinball** [comment]
No need to apologize. It just looked like a premature optimization to me.

**Pull request closed without merging**
