### PR TITLE
allow class to be an object

### PR DESCRIPTION
**Pull request by nordfjord**
After the discussion in #545 I decided to take a stab at implementing the enhancement.

### CODE REVIEW

**Comment by nordfjord** [comment]
now the m function can be used as so: 
```js
var shouldHaveImportantClass = true,
    hasVariableClass = true;
m('div', {
  className: {
    'important-class': shouldHaveImportantClass,
    'variable-class': hasVariableClass ? 'variableClassName' : false
  }
});
// -> <div class="important-class variableClassName"></div>
```

**Comment by Naddiseo** [comment]
Shouldn't this logic go in `setAttributes`? Otherwise you can't use it with a precompiler.

```javascript
function view(ctrl) {
    return { tag: 'div', attrs: { 
    className: {
         'important-class': ctrl.shouldHaveImportantClass,
         'variable-class': ctrl.getVariableClass()
    }
    };
}

```

**Comment by Naddiseo** [comment]
Your current implementation can be significantly improved performance-wise: http://jsperf.com/mithril-pull-753

**Comment by lawrence-dol** [comment]
Without commenting on the value of the overall idea, this implementation seems to contain internal inconsistencies; sometimes the object key is the class, sometimes the object value is. I rather think it should be an object of class-name: boolean pairs. Something along the lines of:

    class: {
        'always-class'   : true,
        'optional-class1': shouldHavaOptional1(),
        'optional-class1': shouldHavaOptional2(),
        'optional-class1': shouldHavaOptional3(),
    }

could emit any of the following depending on the results of the functions:

    <div class="always-class optional-class1"></div>
    <div class="always-class optional-class2"></div>
    <div class="always-class optional-class3"></div>
    ...
    <div class="always-class optional-class1 optional-class2 optional-class3"></div>

But since the class order matters in terms of overriding styles, it really should be an array of objects, where each object is:

    [ { 'class' : "name", enabled: boolean }, ... ]

**Comment by nordfjord** [comment]
@lawrence-dol The reason I wanted to allow the value to be the class was because javascript doesn't allow variable property key's such as:
```js
var importance = '1';

m('div', {
  className: {
    'importance-' + importance: true
  }
});
```

which I thought would be a nice feature.

also I think your idea of an array of objects requires to much code.

I however am less and less convinced this belongs in core.

Barney Caroll had an interesting idea of allowing the extension of arbitrary attributes using `m.attrs` as a container for extensions.

**Comment by barneycarroll** [comment]
@nordfjord sounds like you need ES6 dynamic keys (and maybe string templates):

```javascript
let importance = 1

let className = {
  [ `importance-${ importance }` ] : true
}

console.log( JSON.stringify( className ) )
```

[Check it](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20importance%20%3D%201%0A%0Alet%20className%20%3D%20%7B%0A%20%20%5B%20%60importance-%24%7B%20importance%20%7D%60%20%5D%20%3A%20true%0A%7D%0A%0Aconsole.log(%20JSON.stringify(%20className%20)%20))

**Comment by maranomynet** [comment]
IMO its seems a bit messy to have class-names sometimes be the key and sometimes the value.

Keep it simple and use a stupid truey-falsy check for each key – and if you need variable class-names, just assign them beforehand.

```js
classMap = {
  'static-class': ctrl.isStatic()
};
classMap[ variable + '-class' ] = ctrl.isVariable();

return m('div', { className:classMap });
```

**Comment by nordfjord** [comment]
@maranomynet I agree, I think my reasoning behind it is sound though, it is in fact to reduce cognitive load.

I find it irritating when specifying classes with variable class names to have to go to the top of my view function to create the class object, and later to examine it again.

e.g.

```js
{
    view: function(ctrl){
        classObj = {
            'show': ctrl.show(),
            'cool': ctrl.cool()
        };
        classObj[ctrl.variableclassname] = ctrl.hasVariableClass();
        m('div', {
            class: classObj
        })
    }
}
```

now imagine when the view has become long (in terms of lines of code), I find it just a tiny bit bothersome to then see in the view somewhere `class: classObject` and having to scroll up to see what exactly compromises the classObject

however in the case of:

```js
{
    view: function(ctrl){
        m('div', {
            class: {
                'show': ctrl.show(),
                'cool': ctrl.cool(),
                'variable-class': ctrl.hasVariableClass ? ctrl.variableclassname : false
            }
        })
    }
}
```

API elegance aside I find it immensely useful to be able to see there directly in the view what compromises the class.

This however is a moribund PR and should by all means be removed, I have had my doubts regarding this belonging in core and think that @barneycarroll s suggestion of `m.attrs` is much more useful. So at the moment I'm simply using a class helper where it is needed.

**Pull request closed without merging**
