### PR TITLE
Test for #1146

### PR DESCRIPTION
**Pull request by barneycarroll**

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Ugh...this looks ugly.

**Comment by pygy** [comment]
@barneycarroll [said](https://github.com/lhorie/mithril.js/pull/1153#issuecomment-233278461)

> This works in practice (the original problem case jsbin visibly just works), but not in theory — I couldn't get any lifecycle tests to pass this. I guess I'll have to invoke the autoredraw API…

The problem was with DOM events... mounting only draws the tree being mounted.

Specifically, [run()](https://github.com/lhorie/mithril.js/blob/6da4e973d8f73f75e75d513d217fd35c331093ef/api/mount.js#L12) is a [throttled](https://github.com/lhorie/mithril.js/blob/6da4e973d8f73f75e75d513d217fd35c331093ef/api/autoredraw.js#L6) version of the [callback defined a few lines above](https://github.com/lhorie/mithril.js/blob/6da4e973d8f73f75e75d513d217fd35c331093ef/api/mount.js#L8-L10).

I'm not sure it makes a lot of sense to redraw everything on mount...

**Comment by barneycarroll** [comment]
> I'm not sure it makes a lot of sense to redraw everything on mount…

It does if we consider that the first draw is synchronous and redraws are global in nature, but these are assumptions from v0 and may no longer hold. I'll rewrite this with an explicit lifecycle sequence.

What continues to baffle me is that granular redraw has effectively been introduced as an implementation accident without a usable API :)

**Comment by pygy** [comment]
I'd be surprised if [`root.redraw = run`](https://github.com/lhorie/mithril.js/blob/6da4e973d8f73f75e75d513d217fd35c331093ef/api/autoredraw.js#L18) was an accident (hence #1157 which makes it slightly nicer to use).

I agree the lack of fanfare is surprising, even though they still aren't as granular as #743 (but introducing that probably necessitates a dependency on `api/throttle.js`, either static through `require` (unlikely given the fact that `render/render.js` currently stands on its own) or injected).

**Comment by lhorie** [comment]
`root.redraw` is really just a reference to a function so that it can be unsubscribed (to avoid memory leaks). It can only really be used as a function call in some restricted cases: as root in m.mount where the component does not take arguments, or as the root in m.route, where the topmost vnode creation is handled by the router

It can't handle granular redraws (i.e. it doesn't handle components w/ arguments and non-component vnodes)

**Pull request merged**
