### PR TITLE
Load mithril on mithril.js.org

### PR DESCRIPTION
**Pull request by tivac**
To allow potential users to futz around with `m` in the dev console, no setup required.

image

### CODE REVIEW

**Comment by pygy** [comment]
Excellent, LGTM :-)

**Comment by pygy** [comment]
There was a conflict with #1793, I added this one under since this sounded like something intended  to be placed "at last"

**Comment by tivac** [comment]
Works for me, thanks! Any interest in merging to `master` so it publishes to mithril.js.org?

**Comment by pygy** [comment]
:+1: on both counts, I intended to suggest adding a `root` as well to play with.

**Comment by tivac** [comment]
That sounds like a fine PR for someone other than me to submit :smile:

**Comment by isiahmeadows** [comment]
@orbitbot A dedicated `iframe` page would be better.

**Comment by isiahmeadows** [comment]
@orbitbot I was thinking something along the lines of TypeScript's playground or something similar, a dedicated page. You could also make it a sidebar thing.

Although, hmm...I wonder what @tivac would think of parsing the Markdown client-side and making it a static-ish SPA. Not like I'm expecting it to happen, but just a thought (and Marked is fast enough to make it work).

**Comment by tivac** [comment]
I definitely prefer keeping it simple & accessible as basic HTML.

I'm not completely against a hybrid that can generate static HTML for the initial load and then splat a SPA on top if someone wanted to do that work. I don't want to do that work, for the record.

It ends up sounding like a pain in the butt for the very marginal gain of "it's cool that mithril's site is rendered by mithril itself".

**Comment by isiahmeadows** [comment]
Okay. I'm okay with leaving it as basic HTML; I was just throwing an idea out there. (My blog loads that way already, and it loads very quickly even on mobile, because I lazily parse the Markdown and cache the results.)

**Pull request merged**
