### PR TITLE
Make clone of params object returned by m.param()

### PR DESCRIPTION
**Pull request by jakobdamjensen**
This fixes the indentation errors created in original pull request of #769 

so before going to bed last night I realized that I made a stupid n00b error with pull request #767 . The routeParams object is returned without being cloned so it's possible to change param values returned by param(key) outside mithril. This is not a great side-effect.

This PR fixes that issue by introducing a simple clone function for copying the params object. Also adds a test to ensure this works.

### CODE REVIEW

**Comment by avesus** [comment]
Please, explain *what the cloning is used for*? The explanation should be in commit messages. Also, it is very recommended by a lot of git commit best practices to "merge" (actually, squash) multiple commits into one. Nobody cares about your' indentation fixes. Shure, the PR is very useful, but if you describe it more precisely, your code would be much better peer-reviewed. Thanks!

**Comment by pelonpelon** [comment]
@avesus 
I've had a few commits that I've "corrected" and felt embarrassed to have the old ones lying around. When I have PR 1a,1b, 1c, how do I "squash" them down into one, keeping all pertinent commit messages? I've never worked that one out.

**Comment by isiahmeadows** [comment]
@jakobdamjensen Mind redoing this commit against master? This would've probably been accepted had it not been largely overlooked. :frowning:

**Comment by jakobdamjensen** [comment]
@isiahmeadows sure. Should I close this one and make a new one?

**Comment by isiahmeadows** [comment]
@jakobdamjensen It'll save a *lot* of time, since this is an almost trivial commit.

**Pull request closed without merging**
