### PR TITLE
Acknowledge multiple component creation strategies

### PR DESCRIPTION
**Pull request by JAForbes**
RE: https://gitter.im/lhorie/mithril.js?at=58db36d2ad849bcf422cb1e7

CC @tivac @calainos

### CODE REVIEW

**Comment by isiahmeadows** [comment]
LGTM

**Comment by pygy** [comment]
>  There's no need to install different sets of tools to make different flavors work

This is only true if you target ES6 browsers (or define constructors/prototype manually)...

**Comment by JAForbes** [comment]
@pygy good point!  Updated.

**Comment by pygy** [comment]
Here we go, thanks for the catch, and for the patch!

**Pull request merged**
