### PR TITLE
Clean.log

### PR DESCRIPTION
**Pull request by ludbek**

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Is there a reason this wasn't done in #1776?

**Comment by ludbek** [comment]
Separation of concern? I thought it would be right thing to make separate pull request for this.

**Comment by isiahmeadows** [comment]
Could you redo it on a fresh branch, then? I was reacting based on the "granular update" commit.

**Comment by ludbek** [comment]
`clean.log` is separate branch. :)

**Comment by ludbek** [comment]
Did you mean to include this commit in `granular.update` branch?

**Comment by isiahmeadows** [comment]
@ludbek No. I mean redo the changes against a branch taken from `next` rather than your local `granular.update` feature branch.

**Comment by isiahmeadows** [comment]
Basically, this:

```sh
git checkout next
git branch -d clean.log
git checkout -b clean.log
# redo `console.log` removals
git push -fu origin next
```

**Pull request closed without merging**
