### PR TITLE
Better cleanup when unmounting

### PR DESCRIPTION
**Pull request by pygy**
No need to create a dummy vnode.

### CODE REVIEW

**Comment by lhorie** [comment]
conflict :(

**Comment by pygy** [comment]
No more :-)

**Comment by lhorie** [comment]
wow, that was fast. Awesome :)

**Comment by pygy** [comment]
I was about to say the conflict meant you had been faster still, but the log says this was written before you reverted the deletion, you beat me because of the PR overhead. Rats.

;-)

**Pull request merged**
