### PR TITLE
Simplify condition (check reference instead of toString, cleanup)

### PR DESCRIPTION
**Pull request by impinball**
As a side note, shouldn't this be checked against a whitelist of specific native constructors? Custom `Error` subclasses would fool this either way, but the whitelist will increase the size a little.

Although this might be a moot point when you eventually switch to ES6 promises.

### CODE REVIEW

**Comment by impinball** [comment]
@lhorie Ping

**Comment by Naddiseo** [comment]
This patch is a breaking change for the reason you outline: it behaves differently for subclasses of `Error`.

```javascript

class MyErr extends Error {}

var e = new MyErr();
var type = {}.toString;

console.log(type.call(e) === "[object Error]" && !e.constructor.toString().match(/ Error/)); // false
console.log(type.call(e) === "[object Error]" && e.constructor !== Error); // true

```

**Comment by impinball** [comment]
IMHO, I'm thinking of fixing this to black list the native errors. It's
still breaking, but less so. And it would make more sense. User subclasses
are not themselves usually fatal errors. The current behavior isn't even
consistent when minifying.

**Comment by impinball** [comment]
I actually forgot about this patch...

**Comment by impinball** [comment]
Fixed in #828.

**Pull request closed without merging**
